"""
SoftwareSHM — Concrete SOFTWARE EMULATION of the SecureHardwareModule interface.

NOTE (R3 — MANDATORY LABEL): This is a SOFTWARE EMULATION of hardware security
module behavior. It does NOT provide:
  - Hardware TRNG (uses os.urandom / OS CSPRNG instead)
  - Hardware attestation (quotes are signed in-process, not by a TPM)
  - Hardware-guaranteed zeroization (see zeroization.py for limitations)
  - Hardware key isolation (private keys reside in process memory)

This label must appear in every user-visible string, API response, and log
message that references this module's output, per Global Rule R3.
"""

import os
import time
import socket

from backend.shm.interface import SecureHardwareModule
from backend.shm import entropy as _entropy
from backend.shm import health as _health
from backend.shm import attestation as _attestation
from backend.shm import zeroization as _zeroization
from backend.crypto import kem as _kem


# Software-emulated device identity constants
_DEVICE_ID = f"SoftwareSHM-emulated@{socket.gethostname()}"
_FIRMWARE_HASH = b"\x00" * 32  # Placeholder: no real firmware to hash in software emulation


class SoftwareSHM(SecureHardwareModule):
    """
    SOFTWARE EMULATION of a Secure Hardware Module.

    All operations are performed in-process using standard Python libraries.
    See module docstring for the full list of what this does NOT provide.
    """

    def __init__(self, max_resample_attempts: int = 5):
        # In-process secret store — NOT hardware-isolated (R3)
        self._store: dict[str, bytearray] = {}
        self._max_resample_attempts = max_resample_attempts

    def _sample_health_tested(self, n_bytes: int) -> bytes:
        """
        Draw entropy and apply health tests. Aborts (raises) after max_resample_attempts.
        Implements SP 800-90B abort-and-resample semantics (R5: fail closed).
        """
        for attempt in range(self._max_resample_attempts):
            sample = _entropy.generate_sample(n_bytes)
            if _health.run_all_tests(sample):
                return sample
        raise RuntimeError(
            "SoftwareSHM (software emulation): entropy health test failed after "
            f"{self._max_resample_attempts} resample attempts. Session aborted (R5)."
        )

    def generate_tef(self, session_id: bytes) -> tuple[bytes, bytes]:
        """
        Generate a health-tested TEF (32 bytes) and blinding nonce r (16 bytes).

        NOTE (R3): SOFTWARE EMULATION — entropy from os.urandom(), not hardware TRNG.
        """
        tef = self._sample_health_tested(32)
        r = os.urandom(16)  # nonce does not require health testing — not a TEF
        return tef, r

    def health_test(self, sample: bytes) -> bool:
        """
        Run all SP 800-90B-inspired health tests on the given sample.

        NOTE (R3): Tests operate on software-generated bytes.
        """
        return _health.run_all_tests(sample)

    def generate_kem_keypair(self) -> tuple[bytes, bytes]:
        """
        Generate an ephemeral ML-KEM-1024 keypair via the software-emulated SHM.

        NOTE (R3): Key material generated in-process; no hardware isolation.
        """
        return _kem.generate_keypair()

    def get_attestation_quote(
        self,
        device_id: str,
        firmware_hash: bytes,
        ephemeral_kem_public_key: bytes,
        session_id: bytes,
        timestamp: int,
    ) -> dict:
        """
        Build an attestation quote.

        NOTE (R3): SOFTWARE EMULATION of TPM-style attestation. No hardware PCR measurements.
        """
        return _attestation.build_quote(
            device_id=device_id,
            firmware_hash=firmware_hash,
            ephemeral_kem_public_key=ephemeral_kem_public_key,
            session_id=session_id,
            timestamp=timestamp,
        )

    def sign_attestation(self, quote: dict, signing_sk: bytes) -> bytes:
        """
        Sign the quote with ML-DSA-87.

        NOTE (R3): SOFTWARE EMULATION — signed in-process, not by a hardware security key.
        """
        return _attestation.sign_quote(quote, signing_sk)

    def secure_store(self, key: str, value: bytes) -> None:
        """
        Store a secret in the in-process store as a mutable bytearray.

        NOTE (R3): SOFTWARE EMULATION — stored in process heap, not hardware-protected memory.
        """
        self._store[key] = bytearray(value)

    def zeroize(self, key: str) -> None:
        """
        Best-effort zeroization of a stored secret.

        NOTE (R3): BEST-EFFORT SOFTWARE EMULATION. See zeroization.py for full limitations.
        No hardware-level memory clearing guarantee.
        """
        _zeroization.zeroize_store(self._store, key)

    @property
    def device_id(self) -> str:
        return _DEVICE_ID

    @property
    def firmware_hash(self) -> bytes:
        return _FIRMWARE_HASH
